version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    container_name: app

  frontend:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_docker/nginx/conf.d/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./var/log/nginx/frontend:/var/log/nginx/frontend:cached
    depends_on:
      - app
    container_name: frontend

  backend:
    image: nginx:latest
    ports:
      - "9091:80"
    volumes:
      - .:/var/www/html
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_docker/nginx/conf.d/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./var/log/nginx/backend:/var/log/nginx/backend:cached
    depends_on:
      - app
    container_name: backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2shop
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    ports:
      - "9092:3306"
    volumes:
      - db_data:/var/lib/mysql
    container_name: db

volumes:
  db_data:
